full_name = input('Can I have your full name? ')
age = input('What is your age? ')
hobby = input('What is your favorite activity or hobby? ')
print('Hello ' + full_name)
print('Your age is ' + age)
print('Your hobby is ' + hobby)